### ISSUE TITLE
You test with Big Size image?

### ISSUE THREAD

**Issue by webserveis** [Zeuskartik/MediaSliderView#2]
Good job, your library looks very interesting

Not if you have tried with large images if the app freezes or lag appears when you slide, look at that library to replace the image viewer

https://github.com/Piasy/BigImageViewer

Is compatible with Glide and, allows to detect if the photo could not be downloaded to show one in cache or error etc ...

**Comment by Zeuskartik** [comment]
@webserveis thanks for bringing this to my notice, although I tested it with big and heavy images, the code seemed to work fine and I didn't notice lag of any kind. I shall iterate one more round of testing and if the gallery freezes than I shall surely try to make necessary adjustments.
