### ISSUE TITLE
Start at a particular position from the List.

### ISSUE THREAD

**Issue by tusharpingale04** [Zeuskartik/MediaSliderView#3]
Hi,
Thanks for your awesome work. I need to start the slider at a particular position from my list. Can you tell me how can we do it?

**Comment by Zeuskartik** [comment]
@tusharpingale04 Thanks a lot for your insight, the library as of now doesn't support starting from a particular position, say the third item of your list. Although, I really want to add this feature to the upcoming build. I shall update the build within the next 2-3 days. After that, you will be able to launch the slider from a particular position by passing in the position in the method itself. Let me know how it works then.

**Comment by Zeuskartik** [comment]
hey @tusharpingale04 !! i have updated the build, so that the gallery starts at a particular position provided by the user. Do let me know if you face any difficulties.
