### ISSUE TITLE
Progress bar is still show on Image one

### ISSUE THREAD

**Issue by SaeedBahari** [Zeuskartik/MediaSliderView#4]
Thanks for Ur greet Job!
but have an issue when using Ur library..
I got list of image from Bundle from another activity, everything is OK (loading image , and show them, zoom in or out...)but progress bar is still show on first image!

**Comment by Zeuskartik** [comment]
@SaeedBahari  Thanks for using my library sir, and surely I shall look into the concern raised by you...

**Comment by SaeedBahari** [comment]
this issue is disappear if image list is more than three item and swipe to end of image and return to first image,Progress bar is  gone!
and another thing Ur library version on jitpack is different on this repository

**Comment by Zeuskartik** [comment]
@SaeedBahari i shall look into these issues. thanks a lot for letting me know sir.

**Comment by Zeuskartik** [comment]
The issue has been resolved
